### ISSUE TITLE
Refactor GraphlQl Server implementation

### ISSUE THREAD

**Issue by Persqual** [gamedaoco/gamedao-haiku#34]
## Context
Extend GraphQL API

The GraphQL API needs ongoing development to have a unified codebase. This is an overarching epic collecting tasks which need to be addressed on the route to full GraphQL integration.

## Tasks
- [x] Remove REST Endpoints if an implementation as plain GraphQL resolver makes sense, which is not always the case, especially for external REST data sources (https://github.com/gamedaoco/gamedao-haiku/pull/41)
- [x] Refactor API core, types and resolvers to a dedicated monorepo package to reduce implementation logic in frontend app.  (https://github.com/gamedaoco/gamedao-haiku/pull/41)
- [x] Automatically generate type definitions for networks we are connecting to ( zero, acala )

## Additional Information + Findings
For type generation and also resolvers, validations etc.:
- This package looks neat and it's supported by the community: https://github.com/MichalLytek/type-graphql
- We have to add decorators etc. to our GraphQl interfaces/types and it can generate the schema for you.
- It also delivers a lot of nice-to-have things like clean splitted-up resolvers in classes, DI, Validations.

**Comment by 2075** [comment]
please keep the descriptions unopinionated or fact oriented.

**Comment by 2075** [comment]
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1140449/155887166-a7a1df67-a6a0-4e4e-93a3-9a81642aa834.png">
