### ISSUE TITLE
Stable Release 1.0

### ISSUE THREAD

**Issue by PAkhidue** [gamedaoco/gamedao-haiku#407]
## User Story
As a user I want to have a working stable environment so I can use it to interact with the community, org, campaigns...

## Acceptance Criteria

1. Local env is running again
2. Newest chain version dockerized @2075 (Marco will try to finish it this evening)
3. New graph schema from @vovacha to work with newest structure/interface so we can mock data to it
5. Update local env docker-compose
6. Finish Stable Release 1.0
5.1 Therefore we would also need to finish the new graph not only the schema
5.2 Update error messages when executing extrinsics
5.3 Implement missing proposal types
5.4 Org Dashboard view with mock data or real data? (If so, historcal data is needed from Graph)
5.5 ...

## Additional Information

- [Stable Release 1.0 List](https://www.notion.so/zeroio/Release-1-0-fc7a4b3610324298a36db728e76a648c)

## How to test

1. Run local env docker-compose file
2. Every service should be up
3. Create mock data (SQL Script / maybe write script that creates mock data when running docker initially)
4. Try GameDAO-Haiku Frontend

**Comment by vovacha** [comment]
That's the updated schema: [https://github.com/gamedaoco/gamedao-haiku/blob/vovacha/graph-v1/pkg/squid/schema.graphql](https://github.com/gamedaoco/gamedao-haiku/blob/vovacha/graph-v1/pkg/squid/schema.graphql)

Probably it's not 100% final, but the best approximation I have now.
@PAkhidue @DarkNebula0

**Comment by PAkhidue** [comment]
New Chain version is now dockerized. playzero/subzero:3.1.60 (playzero/subzero:latest)
Next task is to update the local docker dev environment. We need to extend it with a relay chain setup. (I will look for it on the parachain server, I think there was a relay setup, otherwise we ask Marco, Vova or Zhenya.

**Comment by PAkhidue** [comment]
So I've updated the local dev-env (docker). It should working with this PR #408 
The only problem is, we need to follow this guide to setup the parachain (manually) otherwise it won't run:
![image](https://user-images.githubusercontent.com/45153452/192002153-abb1ba05-cb22-4e97-b748-03138521c901.png)
 
But we can work with this for now.

**Comment by PAkhidue** [comment]
I went through the Notion table and tried to write out everything that's missing/not working or should be modified:

- [x] 1. Deploy Graph (@vovacha, support from @DarkNebula0 maybe, depends if we change pipeline now)
- [x] 2. Update FE graph structure changes (@DarkNebula0 @PAkhidue) #415 

3. Org
- [x] 3.1 Update create organisation extrinsic call (New interface of extrinsic is in the file at the end of the comment) #410 
- [ ] 3.2 Treasury missing mock data (merge open PR) #380
- [x] 3.3 Overview fix missing text in "Treasury" Section, "Go To Members" should be "Go To Treasury" #412
4. Gov
- [x] 4.1 Update create proposal extrinsic call (New interface of extrinsic is in the file at the end of the comment) #413
- [x] 4.2 Add spending proposal #399 #359 @Lynnyara @cargre87 do we have a final UI? YES @PAkhidue ->> https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/GameDAO-Haiku-UI?node-id=3685%3A86314 - Start at 12.2
5. Campaign
- [x] 5.1 Update create campaign extrinsic call (New interface of extrinsic is in the file at the end of the comment) #411
- [x] 6. Layout
- [x] 6.1 Fix navigation layout, Organisation no margin to Logo top left corner (Pic. 1) #418
- [ ] 6.2 Fix org/campaign grid, when opening "sort by" page moves in mobile view #417
- [x] 6.3 I think the wallet switcher is confusing in mobile view - avatar confuses at the top of the screen (Pic. 3) #416
- [x] 6.4 Network switch will be hard to reach when we add more items to the wallet switch popup. It's at the bottom of the screen and not scrollable (Pic. 2) #416
7. Links
- [x] 7.1 Footer "Polkadot Explorer" - link to any stable environment when releasing #414
- [x] 7.2 In Mobile view we have documentation link twice, as a link and as button #414
8. Messages/Errors/Success (Show better errors when extrinsic call fails)
- [x] 8.1 Create org #410
- [x] 8.2 Create campaign #411
- [x] 8.3 Create proposal #413
- [x] 8.4 Vote proposal #413
- [x] 8.5 fund campaign #411
- [x] 8.6 Join & Leave Org #410
9. Content Editor
- [x] 9.1 For better image performance in Content Editor we may need an IPFS Image Caching Service #388

Pic. 1:
![Navigation_Screenshot_1](https://user-images.githubusercontent.com/45153452/192312749-45437d19-a52a-433a-bb00-3d353901ee0e.png)

Pic. 2:
![NetworkSwitch_Screenshot_2](https://user-images.githubusercontent.com/45153452/192312751-d6128444-5f46-425f-864d-45df1de0baa7.png)

Pic. 3:
![image](https://user-images.githubusercontent.com/45153452/192324215-7f7a4f7c-1da6-4eb4-9e6d-e750174d6919.png)

Exintrics v59: (it's not the release version, but @vovacha told me the extrinsics won't change in v60/61, the actual release chain version) [extrinsics-v59.txt](https://github.com/gamedaoco/gamedao-haiku/files/9647522/extrinsics-v59.txt)
